name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [16.x]
        
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: |
          sudo npm install yarn -g
          yarn --version
          yarn install
          yarn build 
          sudo cp ~/home/ubuntu/actions-runner/_work/dbms-project-frontend/dbms-project-frontend/build /var/www/html 
          sudo systemctl restart nginx
