name: Deploy

on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  build:

    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [16.x]
        
    steps:
    - uses: actions/checkout@v2
    - name: build and deploy frontend
      run: |
            cd ~/home/ubuntu/actions-runner/_work/dbms-project-frontend/dbms-project-frontend
            yarn
            yarn build 
            sudo cp ~/home/ubuntu/actions-runner/_work/dbms-project-frontend/dbms-project-frontend/build /var/www/html 
            sudo systemctl restart nginx
